# -*- coding: utf-8 -*-
"""house-prices-model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fbNWh0v4U2KJ-nYh_gpNtCNXnHOHi4qU
"""

# Imports
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Carregar o dataset
data = pd.read_csv('/content/drive/MyDrive/Braskem/house_prices.csv')

data.head()

# Separar as variáveis independes e dependentes
X = data.drop('Price', axis=1)
Y = data['Price']

X.head()

Y.head()

# Dividir os dados em conjuntos de treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Criar e treinar o modelo
model = LinearRegression()
model.fit(X_train, y_train)

# Avaliar o modelo
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print(f'Mean Squared Error: {mse}')

# Salvar o modelo
import joblib

joblib.dump(model, '/content/drive/MyDrive/Braskem/modelo_treinado.pkl')